"use client";

import type { EmploymentStatus, PublicRecordKind } from "@/lib/audit/contracts";

export type AuditFieldStep = "income" | "credit" | "history" | "employment" | "review";
export type AuditFormFacts = {
  annualIncome: number;
  monthlyDebt: number;
  loanAmount: number;
  loanTerm: number;
  creditScore: number;
  utilization: number;
  delinq30: number;
  delinq60: number;
  delinq90: number;
  publicRecordKind: PublicRecordKind | "NONE";
  publicRecordMonthsAgo: number;
  inquiries: number;
  employmentMonths: number;
  employmentStatus: EmploymentStatus;
  incomeDocumented: boolean;
};

export const auditSteps: readonly AuditFieldStep[] = ["income", "credit", "history", "employment", "review"];
export const initialAuditFacts: AuditFormFacts = {
  annualIncome: 78000, monthlyDebt: 1150, loanAmount: 12000, loanTerm: 36,
  creditScore: 688, utilization: 34, delinq30: 0, delinq60: 0, delinq90: 0,
  publicRecordKind: "NONE", publicRecordMonthsAgo: 0, inquiries: 2,
  employmentMonths: 42, employmentStatus: "FULL_TIME", incomeDocumented: true,
};

type UpdateFacts = <K extends keyof AuditFormFacts>(key: K, value: AuditFormFacts[K]) => void;
type FieldsProps = { facts: AuditFormFacts; update: UpdateFacts };

const copy: Record<AuditFieldStep, { heading: string; description: string }> = {
  income: {
    heading: "Start with a fictional borrowing request.",
    description: "Use only made-up values. This studio never asks for a person’s name, contact details, account identifiers, SSN, free-text notes, or files.",
  },
  credit: {
    heading: "Now add a synthetic credit profile.",
    description: "These are financial variables the synthetic policy can evaluate. Presentation variants are generated by the audit; you do not enter demographic information.",
  },
  history: {
    heading: "Capture the observable credit history.",
    description: "Public-record categories are deliberately coarse. Do not enter case numbers, addresses, names, or any identifying details.",
  },
  employment: {
    heading: "Finish the policy-relevant employment facts.",
    description: "The tool-guided configuration will use the same fictional facts as the baseline. It changes the decision environment, not the applicant.",
  },
  review: {
    heading: "Review the bounded experiment before it runs.",
    description: "This is an educational diagnostic, not a lending decision, credit advice, a compliance determination, or a population-level fairness result.",
  },
};

function dollars(value: number) {
  return new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 }).format(value);
}

function NumberInput({ label, value, onChange, min, max, step = 1, suffix }: {
  label: string; value: number; onChange: (value: number) => void; min: number; max: number; step?: number; suffix?: string;
}) {
  return <label className="studioField"><span>{label}</span><div>
    <input type="number" min={min} max={max} step={step} value={value}
      onChange={event => onChange(Number(event.target.value))} />
    {suffix && <em>{suffix}</em>}
  </div></label>;
}

function IncomeFields({ facts, update, dti }: FieldsProps & { dti: number }) {
  return <div className="fieldGrid">
    <NumberInput label="Annual income" value={facts.annualIncome} min={0} max={600000}
      onChange={value => update("annualIncome", value)} suffix="USD / year" />
    <NumberInput label="Monthly debt payments" value={facts.monthlyDebt} min={0} max={50000}
      onChange={value => update("monthlyDebt", value)} suffix="USD / month" />
    <NumberInput label="Requested amount" value={facts.loanAmount} min={1000} max={100000}
      onChange={value => update("loanAmount", value)} suffix="USD" />
    <NumberInput label="Requested term" value={facts.loanTerm} min={12} max={60}
      onChange={value => update("loanTerm", value)} suffix="months" />
    <div className="derivedMetric"><span>Debt-to-income</span><strong>{dti}%</strong>
      <small>Derived locally from the fictional values above.</small></div>
  </div>;
}

function CreditFields({ facts, update }: FieldsProps) {
  return <div className="fieldGrid">
    <NumberInput label="Credit score" value={facts.creditScore} min={300} max={850}
      onChange={value => update("creditScore", value)} />
    <NumberInput label="Revolving utilization" value={facts.utilization} min={0} max={100}
      onChange={value => update("utilization", value)} suffix="%" />
    <NumberInput label="30–59 day delinquencies" value={facts.delinq30} min={0} max={20}
      onChange={value => update("delinq30", value)} suffix="in 24 months" />
    <NumberInput label="60–89 day delinquencies" value={facts.delinq60} min={0} max={20}
      onChange={value => update("delinq60", value)} suffix="in 24 months" />
    <NumberInput label="90+ day delinquencies" value={facts.delinq90} min={0} max={20}
      onChange={value => update("delinq90", value)} suffix="in 24 months" />
  </div>;
}

function HistoryFields({ facts, update }: FieldsProps) {
  return <div className="fieldGrid">
    <label className="studioField"><span>Public record category</span><div>
      <select value={facts.publicRecordKind}
        onChange={event => update("publicRecordKind", event.target.value as PublicRecordKind | "NONE")}>
        <option value="NONE">None</option><option value="COLLECTION">Collection</option>
        <option value="TAX_LIEN">Tax lien</option><option value="JUDGMENT">Judgment</option>
        <option value="BANKRUPTCY_CH7">Bankruptcy Chapter 7</option>
        <option value="BANKRUPTCY_CH13">Bankruptcy Chapter 13</option>
      </select>
    </div></label>
    {facts.publicRecordKind !== "NONE" && <NumberInput label="Months since record"
      value={facts.publicRecordMonthsAgo} min={0} max={240}
      onChange={value => update("publicRecordMonthsAgo", value)} suffix="months" />}
    <NumberInput label="Hard inquiries" value={facts.inquiries} min={0} max={20}
      onChange={value => update("inquiries", value)} suffix="in 6 months" />
  </div>;
}

function EmploymentFields({ facts, update }: FieldsProps) {
  return <div className="fieldGrid">
    <NumberInput label="Employment tenure" value={facts.employmentMonths} min={0} max={600}
      onChange={value => update("employmentMonths", value)} suffix="months" />
    <label className="studioField"><span>Employment status</span><div>
      <select value={facts.employmentStatus}
        onChange={event => update("employmentStatus", event.target.value as EmploymentStatus)}>
        <option value="FULL_TIME">Full time</option><option value="PART_TIME">Part time</option>
        <option value="SELF_EMPLOYED">Self-employed</option><option value="CONTRACT">Contract</option>
        <option value="RETIRED">Retired</option><option value="UNEMPLOYED">Unemployed</option>
      </select>
    </div></label>
    <label className="choiceRow"><input type="checkbox" checked={facts.incomeDocumented}
      onChange={event => update("incomeDocumented", event.target.checked)} />
      <span><strong>Income is documented</strong><small>The fictional policy can require verification before citing unverified income.</small></span>
    </label>
  </div>;
}

function AuditReview({ facts, dti, accepted, message, submissionError, onAcceptedChange }: {
  facts: AuditFormFacts;
  dti: number;
  accepted: boolean;
  message: string;
  submissionError: boolean;
  onAcceptedChange: (accepted: boolean) => void;
}) {
  return <div className="reviewCard">
    <div className="reviewFacts"><span>Fictional scenario</span>
      <strong>{dollars(facts.loanAmount)} / {facts.loanTerm} months</strong>
      <p>{dollars(facts.annualIncome)} income · {facts.creditScore} score · {facts.utilization}% utilization · {dti}% DTI</p>
    </div>
    <div className="reviewCompare"><span>Audit design</span><strong>Baseline × platform</strong>
      <p>All six audit families · k=5 · up to $1 per configuration.</p></div>
    <label className="scopeCheck"><input type="checkbox" checked={accepted}
      onChange={event => onAcceptedChange(event.target.checked)} />
      <span>I confirm every value is fictional and I understand this cannot evaluate a real applicant or provide a lending, credit, legal, or compliance outcome.</span>
    </label>
    {message && <p className={submissionError ? "submissionMessage error" : "submissionMessage"}>{message}</p>}
  </div>;
}

export function AuditIntakeStep({ step, facts, dti, accepted, submissionError, message,
  update, onAcceptedChange }: {
  step: AuditFieldStep;
  facts: AuditFormFacts;
  dti: number;
  accepted: boolean;
  submissionError: boolean;
  message: string;
  update: UpdateFacts;
  onAcceptedChange: (accepted: boolean) => void;
}) {
  const { heading, description } = copy[step];
  return <>
    <div className="assistantMessage"><span className="assistantAvatar">A</span><div>
      <p className="messageMeta">AUDIT GUIDE</p>
      <h1 id="audit-studio-step-heading" tabIndex={-1}>{heading}</h1>
      <p>{description}</p>
    </div></div>
    <div className="userComposer">
      {step === "income" && <IncomeFields facts={facts} update={update} dti={dti} />}
      {step === "credit" && <CreditFields facts={facts} update={update} />}
      {step === "history" && <HistoryFields facts={facts} update={update} />}
      {step === "employment" && <EmploymentFields facts={facts} update={update} />}
      {step === "review" && <AuditReview facts={facts} dti={dti} accepted={accepted}
        message={message} submissionError={submissionError} onAcceptedChange={onAcceptedChange} />}
    </div>
  </>;
}
